name: java-webapp-build

on:
  push:
    paths: # only changes in listed paths will trigger workflow
      - ".github/workflows/java-webapp-build.yml"
      - "src/main/java/com/darekgw/WorkflowTestJavaApp/**"
  workflow_dispatch:

jobs:
  build:
    name: build-java-webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test
